// src/utils/excelGenerator.js
import * as XLSX from 'xlsx'
import { calculateGrade, getPercentage } from './gradeCalculator'
import { format } from 'date-fns'

/**
 * Full student report
 */
export const generateStudentReport = (student, classData, attendanceRecords, marksWithExam, teacher) => {
  const wb = XLSX.utils.book_new()

  const total = attendanceRecords.length
  const present = attendanceRecords.filter(r => r.status === 'Present').length
  const absent  = attendanceRecords.filter(r => r.status === 'Absent').length
  const late    = attendanceRecords.filter(r => r.status === 'Late').length
  const attPct  = total > 0 ? ((present / total) * 100).toFixed(1) : '0.0'

  const rows = []
  rows.push(['EduDesk — Student Academic Report'])
  rows.push([])
  rows.push(['Student Name', student.name, '', 'Roll Number', student.rollNumber])
  rows.push(['Class', `${classData.className} - ${classData.section}`, '', 'Report Date', format(new Date(), 'dd MMM yyyy')])
  rows.push(['Parent Name', student.parentName])
  rows.push([])
  rows.push(['ATTENDANCE SUMMARY'])
  rows.push(['Total Days', 'Present', 'Absent', 'Late', 'Attendance %'])
  rows.push([total, present, absent, late, `${attPct}%`])
  rows.push([])
  rows.push(['EXAM RESULTS'])
  rows.push(['Exam Name', 'Subject', 'Max Marks', 'Marks Obtained', 'Percentage', 'Grade', 'Remarks'])
  marksWithExam.forEach(m => {
    const pct = getPercentage(m.marksObtained, m.maxMarks)
    const { grade } = calculateGrade(m.marksObtained, m.maxMarks)
    rows.push([m.examName, m.subject, m.maxMarks, m.marksObtained, `${pct}%`, grade, m.remarks || ''])
  })
  rows.push([])
  rows.push(['Teacher', teacher.name, '', 'School', teacher.school || ''])
  rows.push(['Generated by EduDesk', '', '', '', format(new Date(), 'dd MMM yyyy, hh:mm a')])

  const ws = XLSX.utils.aoa_to_sheet(rows)
  ws['!cols'] = [{ wch: 18 }, { wch: 22 }, { wch: 4 }, { wch: 16 }, { wch: 20 }]
  XLSX.utils.book_append_sheet(wb, ws, 'Full Report')

  // Subject-wise sheets
  const subjectGroups = {}
  marksWithExam.forEach(m => {
    if (!subjectGroups[m.subject]) subjectGroups[m.subject] = []
    subjectGroups[m.subject].push(m)
  })

  Object.entries(subjectGroups).forEach(([subject, marks]) => {
    const subRows = []
    subRows.push([`Subject Report: ${subject}`])
    subRows.push(['Student:', student.name, 'Class:', `${classData.className} - ${classData.section}`])
    subRows.push([])
    subRows.push(['Exam Name', 'Max Marks', 'Marks Obtained', 'Percentage', 'Grade', 'Remarks'])
    marks.forEach(m => {
      const pct = getPercentage(m.marksObtained, m.maxMarks)
      const { grade } = calculateGrade(m.marksObtained, m.maxMarks)
      subRows.push([m.examName, m.maxMarks, m.marksObtained, `${pct}%`, grade, m.remarks || ''])
    })
    const totalMarks = marks.reduce((a, m) => a + m.maxMarks, 0)
    const obtainedMarks = marks.reduce((a, m) => a + m.marksObtained, 0)
    const subAvg = totalMarks > 0 ? ((obtainedMarks / totalMarks) * 100).toFixed(1) : '0.0'
    const { grade: overallGrade } = calculateGrade(obtainedMarks, totalMarks)
    subRows.push([])
    subRows.push(['OVERALL', totalMarks, obtainedMarks, `${subAvg}%`, overallGrade, ''])

    const subWs = XLSX.utils.aoa_to_sheet(subRows)
    subWs['!cols'] = [{ wch: 20 }, { wch: 12 }, { wch: 16 }, { wch: 12 }, { wch: 8 }, { wch: 20 }]
    const sheetName = subject.substring(0, 31) // Excel sheet name limit
    XLSX.utils.book_append_sheet(wb, subWs, sheetName)
  })

  const monthYear = format(new Date(), 'MMM_yyyy')
  const fileName = `${student.name.replace(/\s+/g, '_')}_Report_${monthYear}.xlsx`
  XLSX.writeFile(wb, fileName)
  return fileName
}

/**
 * Subject-wise class report
 */
export const generateSubjectReport = (subject, classData, students, marksMap, teacher) => {
  const wb = XLSX.utils.book_new()
  const rows = []
  rows.push([`Subject Report: ${subject}`])
  rows.push(['Class:', `${classData.className} - ${classData.section}`, 'Teacher:', teacher.name])
  rows.push(['School:', teacher.school || '', 'Date:', format(new Date(), 'dd MMM yyyy')])
  rows.push([])
  rows.push(['Roll No.', 'Student Name', 'Max Marks', 'Marks Obtained', 'Percentage', 'Grade', 'Remarks'])
  students.forEach(s => {
    const m = marksMap[s.id]
    if (m) {
      const pct = getPercentage(m.marksObtained, m.maxMarks)
      const { grade } = calculateGrade(m.marksObtained, m.maxMarks)
      rows.push([s.rollNumber, s.name, m.maxMarks, m.marksObtained, `${pct}%`, grade, m.remarks || ''])
    } else {
      rows.push([s.rollNumber, s.name, '-', 'Absent/NA', '-', '-', ''])
    }
  })

  const ws = XLSX.utils.aoa_to_sheet(rows)
  ws['!cols'] = [{ wch: 10 }, { wch: 22 }, { wch: 12 }, { wch: 16 }, { wch: 12 }, { wch: 8 }, { wch: 20 }]
  XLSX.utils.book_append_sheet(wb, ws, subject.substring(0, 31))

  const fileName = `${subject.replace(/\s+/g, '_')}_Class_Report_${format(new Date(), 'MMM_yyyy')}.xlsx`
  XLSX.writeFile(wb, fileName)
  return fileName
}
